"""
Base Memory System Implementation

Core memory management functionality for the SERRA ORGIN framework.
Provides persistent storage, retrieval, and management of agent memories,
interactions, and learning data.
"""

import asyncio
import json
from datetime import datetime, timedelta
from typing import Dict, List, Optional, Any, Union
from dataclasses import dataclass
from enum import Enum

from loguru import logger
from pydantic import BaseModel

from serra_orgin.database import DatabaseManager


class MemoryType(Enum):
    """Types of memory entries"""
    INTERACTION = "interaction"
    LEARNING = "learning"
    TOOL = "tool"
    COMMUNICATION = "communication"
    CONTEXT = "context"
    SHARED_DATA = "shared_data"


@dataclass
class MemoryEntry:
    """Individual memory entry"""
    id: Optional[str]
    agent_id: str
    memory_type: MemoryType
    content: Dict[str, Any]
    timestamp: datetime
    importance: float  # 0.0 to 1.0
    access_count: int = 0
    last_accessed: Optional[datetime] = None
    tags: List[str] = None
    
    def __post_init__(self):
        if self.tags is None:
            self.tags = []


class MemoryStats(BaseModel):
    """Memory system statistics"""
    total_entries: int = 0
    entries_by_type: Dict[str, int] = {}
    avg_importance: float = 0.0
    total_size_bytes: int = 0
    oldest_entry: Optional[datetime] = None
    newest_entry: Optional[datetime] = None


class MemorySystem:
    """
    Core memory management system for SERRA ORGIN
    
    Handles persistent storage and retrieval of all system memories
    including agent interactions, learning data, and shared information.
    """
    
    def __init__(self, db: DatabaseManager, max_size: int = 10000):
        self.db = db
        self.max_size = max_size
        self.memory_cache: Dict[str, MemoryEntry] = {}
        self.stats = MemoryStats()
        
        logger.info("🧠 Memory System initialized")
    
    async def initialize(self):
        """Initialize the memory system"""
        try:
            # Create memory tables if they don't exist
            await self._create_tables()
            
            # Load recent memories into cache
            await self._load_cache()
            
            # Update statistics
            await self._update_stats()
            
            logger.success("✅ Memory System ready")
            
        except Exception as e:
            logger.error(f"❌ Failed to initialize memory system: {e}")
            raise
    
    async def store(
        self,
        agent_id: str,
        memory_type: MemoryType,
        content: Dict[str, Any],
        importance: float = 0.5,
        tags: Optional[List[str]] = None
    ) -> str:
        """Store a new memory entry"""
        
        entry = MemoryEntry(
            id=None,  # Will be generated by database
            agent_id=agent_id,
            memory_type=memory_type,
            content=content,
            timestamp=datetime.utcnow(),
            importance=importance,
            tags=tags or []
        )
        
        # Store in database
        entry_id = await self._store_to_db(entry)
        entry.id = entry_id
        
        # Add to cache
        self._add_to_cache(entry)
        
        # Cleanup if needed
        await self._cleanup_if_needed()
        
        logger.debug(f"📝 Stored memory entry: {entry_id}")
        return entry_id
    
    async def retrieve(
        self,
        agent_id: Optional[str] = None,
        memory_type: Optional[MemoryType] = None,
        tags: Optional[List[str]] = None,
        limit: int = 100,
        min_importance: float = 0.0
    ) -> List[MemoryEntry]:
        """Retrieve memory entries based on criteria"""
        
        entries = []
        
        # Build query criteria
        criteria = {}
        if agent_id:
            criteria['agent_id'] = agent_id
        if memory_type:
            criteria['memory_type'] = memory_type.value
        if min_importance > 0:
            criteria['importance'] = f">={min_importance}"
        
        # Get from database
        db_entries = await self._retrieve_from_db(criteria, limit)
        
        for entry_data in db_entries:
            entry = self._dict_to_memory_entry(entry_data)
            
            # Filter by tags if specified
            if tags and not any(tag in entry.tags for tag in tags):
                continue
                
            # Update access statistics
            entry.access_count += 1
            entry.last_accessed = datetime.utcnow()
            await self._update_access_stats(entry.id)
            
            entries.append(entry)
        
        logger.debug(f"🔍 Retrieved {len(entries)} memory entries")
        return entries
    
    async def search(
        self,
        query: str,
        agent_id: Optional[str] = None,
        limit: int = 50
    ) -> List[MemoryEntry]:
        """Search memories by content"""
        
        # For now, simple text search - could be enhanced with semantic search
        entries = await self.retrieve(agent_id=agent_id, limit=limit * 2)
        
        matching_entries = []
        query_lower = query.lower()
        
        for entry in entries:
            content_str = json.dumps(entry.content).lower()
            if query_lower in content_str:
                matching_entries.append(entry)
                
            if len(matching_entries) >= limit:
                break
        
        logger.debug(f"🔎 Found {len(matching_entries)} entries matching query")
        return matching_entries
    
    async def delete(self, entry_id: str) -> bool:
        """Delete a memory entry"""
        try:
            # Remove from database
            await self._delete_from_db(entry_id)
            
            # Remove from cache
            if entry_id in self.memory_cache:
                del self.memory_cache[entry_id]
            
            logger.debug(f"🗑️ Deleted memory entry: {entry_id}")
            return True
            
        except Exception as e:
            logger.error(f"❌ Failed to delete memory entry {entry_id}: {e}")
            return False
    
    async def cleanup_old_data(self, older_than_days: int = 30):
        """Clean up old, low-importance memories"""
        
        cutoff_date = datetime.utcnow() - timedelta(days=older_than_days)
        
        # Delete old, low-importance entries
        deleted_count = await self._cleanup_old_entries(cutoff_date, max_importance=0.3)
        
        logger.info(f"🧹 Cleaned up {deleted_count} old memory entries")
        
        # Update statistics
        await self._update_stats()
    
    async def get_size(self) -> int:
        """Get total number of memory entries"""
        return self.stats.total_entries
    
    async def get_stats(self) -> MemoryStats:
        """Get memory system statistics"""
        await self._update_stats()
        return self.stats
    
    async def shutdown(self):
        """Shutdown memory system"""
        # Save any pending cache entries
        logger.info("🛑 Shutting down memory system")
        
        # Clear cache
        self.memory_cache.clear()
        
        logger.success("✅ Memory system shutdown complete")
    
    # Store-specific methods for different types
    
    async def store_interaction(self, interaction_data: Dict[str, Any]) -> str:
        """Store an interaction memory"""
        return await self.store(
            agent_id=interaction_data.get('agent_id', 'system'),
            memory_type=MemoryType.INTERACTION,
            content=interaction_data,
            importance=0.7,  # Interactions are fairly important
            tags=['interaction', 'user']
        )
    
    async def store_learning_entry(self, learning_data: Dict[str, Any]) -> str:
        """Store a learning memory"""
        return await self.store(
            agent_id=learning_data.get('agent_id', 'system'),
            memory_type=MemoryType.LEARNING,
            content=learning_data,
            importance=0.9,  # Learning data is very important
            tags=['learning', 'improvement']
        )
    
    # Private methods
    
    async def _create_tables(self):
        """Create necessary database tables"""
        create_query = """
        CREATE TABLE IF NOT EXISTS memories (
            id TEXT PRIMARY KEY,
            agent_id TEXT NOT NULL,
            memory_type TEXT NOT NULL,
            content TEXT NOT NULL,
            importance REAL NOT NULL,
            timestamp DATETIME NOT NULL,
            access_count INTEGER DEFAULT 0,
            last_accessed DATETIME,
            tags TEXT
        );
        
        CREATE INDEX IF NOT EXISTS idx_agent_id ON memories(agent_id);
        CREATE INDEX IF NOT EXISTS idx_memory_type ON memories(memory_type);
        CREATE INDEX IF NOT EXISTS idx_importance ON memories(importance);
        CREATE INDEX IF NOT EXISTS idx_timestamp ON memories(timestamp);
        """
        
        await self.db.execute(create_query)
    
    async def _store_to_db(self, entry: MemoryEntry) -> str:
        """Store memory entry to database"""
        entry_id = f"mem_{datetime.utcnow().timestamp()}_{entry.agent_id}"
        
        query = """
        INSERT INTO memories (id, agent_id, memory_type, content, importance, timestamp, tags)
        VALUES (?, ?, ?, ?, ?, ?, ?)
        """
        
        await self.db.execute(query, (
            entry_id,
            entry.agent_id,
            entry.memory_type.value,
            json.dumps(entry.content),
            entry.importance,
            entry.timestamp,
            json.dumps(entry.tags)
        ))
        
        return entry_id
    
    async def _retrieve_from_db(
        self, 
        criteria: Dict[str, Any], 
        limit: int
    ) -> List[Dict[str, Any]]:
        """Retrieve memory entries from database"""
        
        where_clauses = []
        params = []
        
        for key, value in criteria.items():
            if key == 'importance' and isinstance(value, str) and value.startswith('>='):
                where_clauses.append(f"{key} >= ?")
                params.append(float(value[2:]))
            else:
                where_clauses.append(f"{key} = ?")
                params.append(value)
        
        where_clause = " AND ".join(where_clauses) if where_clauses else "1=1"
        
        query = f"""
        SELECT * FROM memories 
        WHERE {where_clause}
        ORDER BY importance DESC, timestamp DESC
        LIMIT ?
        """
        params.append(limit)
        
        return await self.db.fetch_all(query, params)
    
    async def _delete_from_db(self, entry_id: str):
        """Delete memory entry from database"""
        query = "DELETE FROM memories WHERE id = ?"
        await self.db.execute(query, (entry_id,))
    
    async def _update_access_stats(self, entry_id: str):
        """Update access statistics for an entry"""
        query = """
        UPDATE memories 
        SET access_count = access_count + 1, last_accessed = ?
        WHERE id = ?
        """
        await self.db.execute(query, (datetime.utcnow(), entry_id))
    
    async def _cleanup_old_entries(self, cutoff_date: datetime, max_importance: float) -> int:
        """Clean up old, low-importance entries"""
        query = """
        DELETE FROM memories 
        WHERE timestamp < ? AND importance <= ?
        """
        
        result = await self.db.execute(query, (cutoff_date, max_importance))
        return result.rowcount if hasattr(result, 'rowcount') else 0
    
    async def _update_stats(self):
        """Update memory system statistics"""
        # Get total count
        count_result = await self.db.fetch_one("SELECT COUNT(*) as count FROM memories")
        self.stats.total_entries = count_result['count'] if count_result else 0
        
        # Get counts by type
        type_query = "SELECT memory_type, COUNT(*) as count FROM memories GROUP BY memory_type"
        type_results = await self.db.fetch_all(type_query)
        self.stats.entries_by_type = {
            row['memory_type']: row['count'] for row in type_results
        }
        
        # Get average importance
        avg_query = "SELECT AVG(importance) as avg_importance FROM memories"
        avg_result = await self.db.fetch_one(avg_query)
        self.stats.avg_importance = avg_result['avg_importance'] if avg_result else 0.0
        
        # Get date range
        date_query = "SELECT MIN(timestamp) as oldest, MAX(timestamp) as newest FROM memories"
        date_result = await self.db.fetch_one(date_query)
        if date_result:
            self.stats.oldest_entry = date_result['oldest']
            self.stats.newest_entry = date_result['newest']
    
    async def _load_cache(self, cache_size: int = 100):
        """Load recent high-importance memories into cache"""
        query = """
        SELECT * FROM memories 
        ORDER BY importance DESC, timestamp DESC 
        LIMIT ?
        """
        
        entries = await self.db.fetch_all(query, (cache_size,))
        
        for entry_data in entries:
            entry = self._dict_to_memory_entry(entry_data)
            self.memory_cache[entry.id] = entry
    
    def _add_to_cache(self, entry: MemoryEntry):
        """Add entry to cache, removing oldest if cache is full"""
        if len(self.memory_cache) >= self.max_size // 10:  # Cache 10% of max size
            # Remove oldest cached entry
            oldest_id = min(
                self.memory_cache.keys(),
                key=lambda k: self.memory_cache[k].timestamp
            )
            del self.memory_cache[oldest_id]
        
        self.memory_cache[entry.id] = entry
    
    def _dict_to_memory_entry(self, data: Dict[str, Any]) -> MemoryEntry:
        """Convert database dict to MemoryEntry object"""
        return MemoryEntry(
            id=data['id'],
            agent_id=data['agent_id'],
            memory_type=MemoryType(data['memory_type']),
            content=json.loads(data['content']),
            timestamp=data['timestamp'],
            importance=data['importance'],
            access_count=data.get('access_count', 0),
            last_accessed=data.get('last_accessed'),
            tags=json.loads(data.get('tags', '[]'))
        )
    
    async def _cleanup_if_needed(self):
        """Clean up memory if approaching size limits"""
        if self.stats.total_entries > self.max_size:
            # Remove oldest, lowest importance entries
            cleanup_count = self.stats.total_entries - int(self.max_size * 0.8)
            
            query = """
            DELETE FROM memories 
            WHERE id IN (
                SELECT id FROM memories 
                ORDER BY importance ASC, timestamp ASC 
                LIMIT ?
            )
            """
            
            await self.db.execute(query, (cleanup_count,))
            
            logger.info(f"🧹 Auto-cleaned {cleanup_count} memory entries")
            await self._update_stats()


class AgentMemory:
    """
    Agent-specific memory interface
    
    Provides a simplified interface for individual agents to manage
    their own memories without accessing the global memory system directly.
    """
    
    def __init__(self, agent_id: str, database: DatabaseManager):
        self.agent_id = agent_id
        self.memory_system = MemorySystem(database)
        
    async def initialize(self):
        """Initialize agent memory"""
        await self.memory_system.initialize()
    
    async def store_request(self, request: str, context: Optional[Dict[str, Any]] = None):
        """Store a user request"""
        content = {
            "request": request,
            "context": context or {},
            "type": "user_request"
        }
        
        return await self.memory_system.store(
            agent_id=self.agent_id,
            memory_type=MemoryType.INTERACTION,
            content=content,
            importance=0.6,
            tags=['request', 'user']
        )
    
    async def store_tool(self, tool: 'Tool'):
        """Store a tool for future use"""
        content = {
            "tool_name": tool.name,
            "tool_description": tool.description,
            "tool_code": tool.code,
            "tool_type": tool.tool_type
        }
        
        return await self.memory_system.store(
            agent_id=self.agent_id,
            memory_type=MemoryType.TOOL,
            content=content,
            importance=0.8,
            tags=['tool', 'dynamic']
        )
    
    async def get_tool(self, tool_name: str) -> Optional['Tool']:
        """Retrieve a stored tool"""
        entries = await self.memory_system.retrieve(
            agent_id=self.agent_id,
            memory_type=MemoryType.TOOL
        )
        
        for entry in entries:
            if entry.content.get('tool_name') == tool_name:
                # Reconstruct tool (would need Tool class import)
                # For now, return None
                return None
        
        return None
    
    async def store_communication(
        self,
        target_agent_id: str,
        message: str,
        response: Dict[str, Any]
    ):
        """Store inter-agent communication"""
        content = {
            "target_agent": target_agent_id,
            "message": message,
            "response": response,
            "timestamp": datetime.utcnow().isoformat()
        }
        
        return await self.memory_system.store(
            agent_id=self.agent_id,
            memory_type=MemoryType.COMMUNICATION,
            content=content,
            importance=0.5,
            tags=['communication', 'inter-agent']
        )
    
    async def store_shared_data(self, sender_id: str, data: Dict[str, Any]):
        """Store data shared from another agent"""
        content = {
            "sender": sender_id,
            "data": data,
            "received_at": datetime.utcnow().isoformat()
        }
        
        return await self.memory_system.store(
            agent_id=self.agent_id,
            memory_type=MemoryType.SHARED_DATA,
            content=content,
            importance=0.7,
            tags=['shared', 'data', sender_id]
        )
    
    async def store_learning_entry(self, learning_data: Dict[str, Any]):
        """Store learning data"""
        return await self.memory_system.store_learning_entry({
            **learning_data,
            "agent_id": self.agent_id
        })
    
    async def save_learning_data(self, learning_data: Dict[str, Any]):
        """Save agent's learning data"""
        return await self.store_learning_entry(learning_data)
    
    async def get_recent_interactions(self, limit: int = 10) -> List[MemoryEntry]:
        """Get recent interactions for context"""
        return await self.memory_system.retrieve(
            agent_id=self.agent_id,
            memory_type=MemoryType.INTERACTION,
            limit=limit
        )
    
    async def search_memories(self, query: str, limit: int = 20) -> List[MemoryEntry]:
        """Search agent's memories"""
        return await self.memory_system.search(
            query=query,
            agent_id=self.agent_id,
            limit=limit
        )
    
    async def shutdown(self):
        """Shutdown agent memory"""
        await self.memory_system.shutdown()
